var firstName = 'Aubrey';
var lastName = 'Badger';
var fullName = `${firstName} ${lastName}`;
var emailAddress = 'akbadger@gmail.com';
var grewUpInCity = true;
var yearsInCollege = 4;
var numberOfPets = 2;
var sleepAverage = parseFloat('8 hours of sleep');
var musicPreference = 'hip-hop';
var favoriteShowsAndMovies = [`Only Lovers Left Alive`, `Moonlight`, `Adventure Time`, `Black Mirror`];
var jobTitleInFiveYears;
var lifeWithoutJavascript = null;
var graduationYear = new Date(2005, 0, 20);

console.log(firstName);
console.log(lastName);
console.log(fullName);
console.log(emailAddress);
console.log(grewUpInCity);
console.log(yearsInCollege);
console.log(numberOfPets);
console.log(sleepAverage);
console.log(musicPreference);
console.log(favoriteShowsAndMovies);
console.log(jobTitleInFiveYears);
console.log(lifeWithoutJavascript);
console.log(graduationYear);